export const COLORS = {
  slate: "#262626",
  secondhand: "#3f3f3f",
  whitish: "#f5f5f5",
  lightGrey: "#dcdcdc",
  accent: "#c8a97e",
  accentDark: "#a07850",
  danger: "#c0392b",
  success: "#27ae60",
  warning: "#e67e22",
  info: "#2980b9",
};

export const S = {
  app: {
    minHeight: "100vh",
    background: COLORS.slate,
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    color: COLORS.whitish,
  },
  card: {
    background: COLORS.secondhand,
    border: `1px solid #555`,
    borderRadius: 12,
    padding: "1.5rem",
  },
  input: {
    width: "100%",
    background: COLORS.slate,
    border: `1px solid #555`,
    borderRadius: 8,
    padding: "10px 14px",
    color: COLORS.whitish,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.2s",
  },
  btn: (variant = "primary") => ({
    padding: "10px 20px",
    borderRadius: 8,
    border: "none",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s",
    background: variant === "primary" ? COLORS.accent : variant === "danger" ? COLORS.danger : variant === "success" ? COLORS.success : variant === "ghost" ? "transparent" : COLORS.secondhand,
    color: variant === "ghost" ? COLORS.lightGrey : variant === "primary" ? COLORS.slate : COLORS.whitish,
    border: variant === "ghost" ? `1px solid #555` : "none",
  }),
  badge: (color) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    background: color === "pending" ? "#3a2a10" : color === "inprogress" ? "#102a3a" : color === "completed" ? "#0e2e1a" : color === "approved" ? "#0e2e1a" : color === "rejected" ? "#2e0e0e" : "#2a2a2a",
    color: color === "pending" ? COLORS.warning : color === "inprogress" ? COLORS.info : color === "completed" ? COLORS.success : color === "approved" ? COLORS.success : color === "rejected" ? COLORS.danger : COLORS.lightGrey,
    border: `1px solid ${color === "pending" ? COLORS.warning : color === "inprogress" ? COLORS.info : color === "completed" ? COLORS.success : color === "approved" ? COLORS.success : color === "rejected" ? COLORS.danger : "#555"}30`,
  }),
};